=== mbrucher/Fesapi/gsoap/PropertyTypeMapping.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.f2i-consulting.com/PropertyTypeMapping" xmlns:ptm="http://www.f2i-consulting.com/PropertyTypeMapping" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:resqml="http://www.energistics.org/energyml/data/resqmlv2" elementFormDefault="qualified">
	<xsd:import namespace="http://www.energistics.org/energyml/data/resqmlv2" schemaLocation="RESQML_SCHEMA_LOCATION/Common.xsd"/>
	<xsd:element name="standardEnergisticsPropertyTypeSet" type="ptm:standardEnergisticsPropertyTypeSet">
		<xsd:annotation>
			<xsd:documentation>A container for enumeration lists.</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<!--                                                         -->
	<xsd:complexType name="standardEnergisticsPropertyTypeSet">
		<xsd:sequence>
			<xsd:element name="standardEnergisticsPropertyType" type="ptm:standardEnergisticsPropertyType" minOccurs="1" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>A single enumeration list.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<!--                                                         -->
	<xsd:complexType name="standardEnergisticsPropertyType">
		<xsd:sequence>
			<xsd:element name="name" type="resqml:ResqmlPropertyKind" minOccurs="1" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>The name of the value.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="description" type="xsd:string" minOccurs="0" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>A description of the value. </xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="version" type="xsd:string" minOccurs="0" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>The version when the value was added.
					The string should match the content of the root version attribute of the schema.
					For example, "1.4.0.0".</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="deprecated" type="xsd:string" minOccurs="0" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>A non blank version indicates that the value has
					been deprecated and may be removed in future versions.
					The string should match the content of the root version attribute of the schema.
					For example, "1.4.0.0".</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="replacedBy" type="xsd:string" minOccurs="0" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>The value to use as a replacement for a deprecated value.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="isAbstract" type="xsd:boolean" minOccurs="0" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>True ("1" or "true") indicates that the property is abstract and cannot be used to characterize a value.
					False ("0" or "false") or not given indicates a non-abstract property that can be instantiated.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="parentKind" type="xsd:string" minOccurs="0" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>Points to a parent property kind</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:choice minOccurs="0">
				<xsd:sequence>
					<xsd:element name="unitOfMeasure" type="xsd:string" minOccurs="1" maxOccurs="1">
						<xsd:annotation>
							<xsd:documentation>The allowed unit of measure for the continuous property.</xsd:documentation>
						</xsd:annotation>
					</xsd:element>
					<xsd:element name="dimensionalClass" type="xsd:string" minOccurs="1" maxOccurs="1">
						<xsd:annotation>
							<xsd:documentation>The dimensional analysis of the unit of measure. 
							For example, a meter (m) would be of class "L", which represents length. 
							A foot (ft) would also be in this dimension.
							Note that angle       is considered to be dimensionless ratio of length.
							Note that solid angle is considered to be dimensionless ratio of area.
							The following nomenclature is used: 
								A = angle 			(SI unit = radian) 
								B = luminous intensity 		(SI unit = candela)
								C = electrical current 		(SI unit = ampere)
								K = thermodynamic temperature 	(SI unit = kelvin)
								L = length 			(SI unit = metre)
								M = mass 			(SI unit = kilogram)
								N = amount of substance 	(SI unit = mole)
								S = solid angle 		(SI unit = steradian)
								T = time 			(SI unit = second)
								1 = dimensionless
								2 = squared			(e.g., "M2")
								3 = cubed
								4 = 4th power
								5 = 5th power
								6 = 6th power
								7 = 7th power
								8 = 8th power
								/ = division
								ratio(X) = A dimensionless ratio of another dimension. 
								        For example, a dimensionless ratio of area would be indicated by "ratio(L2)" and represents the equivalent of "L2/L2".
									This is only used when the underlying dimension would otherwise be "1".
							The values may be broken into numerator and denominator separated by a slash "/" but multiple slashes must not be used. 
							A slash must not terminate the string.
							For example, length per time would be indicated by "L/T"
							A number other than "1" will always follow a single dimensional character (e.g., "M2") and will represent the power of that component.
							The number "1" will only exist by itself or as the whole numerator (e.g., "1" or "1/T"). 
							The number "1" must not be used as a denominator because it is implied (e.g., "M" impiles "M/1").
							For consistency, the items within a numerator or denominator are listed in alphabetical order (i.e., LM - not ML).</xsd:documentation>
						</xsd:annotation>
					</xsd:element>
				</xsd:sequence>
				<xsd:sequence>
					<xsd:element name="minimumValue" type="xsd:long" minOccurs="0" maxOccurs="1">
						<xsd:annotation>
							<xsd:documentation>The minimum value allowed for the discrete property.</xsd:documentation>
						</xsd:annotation>
					</xsd:element>
					<xsd:element name="maximumValue" type="xsd:long" minOccurs="0" maxOccurs="1">
						<xsd:annotation>
							<xsd:documentation>The maximum value allowed for the discrete property.</xsd:documentation>
						</xsd:annotation>
					</xsd:element>
				</xsd:sequence>
				<xsd:sequence>
					<xsd:element name="enumValue" type="xsd:string" minOccurs="0" maxOccurs="unbounded">
						<xsd:annotation>
							<xsd:documentation>A value allowed for the categorical property.</xsd:documentation>
						</xsd:annotation>
					</xsd:element>
				</xsd:sequence>
			</xsd:choice>
			<xsd:element name="equivalentPropertyType" type="ptm:equivalentPropertyType" minOccurs="0" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>The name of the value.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>	
	<!--                                                         -->
	<xsd:complexType name="equivalentPropertyType">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string" minOccurs="1" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>The name of the value.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="namingSystem" type="xsd:string" minOccurs="1" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>The name of the value.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</schema>

=== mbrucher/Fesapi/resources/PropertyTypeMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<standardEnergisticsPropertyTypeSet xmlns="http://www.f2i-consulting.com/PropertyTypeMapping" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.f2i-consulting.com/PropertyTypeMapping PropertyTypeMapping.xsd ">
	<standardEnergisticsPropertyType>
		<name>absorbed dose</name>
		<description>The amount of energy absorbed per mass.</description>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
		<unitOfMeasure>Gy</unitOfMeasure>
		<dimensionalClass>L2/T2</dimensionalClass>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>acceleration linear</name>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
		<unitOfMeasure>m/s2</unitOfMeasure>
		<dimensionalClass>L/T2</dimensionalClass>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>activity (of radioactivity)</name>
		<description>A measure of the radiation being emitted.</description>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
		<unitOfMeasure>Bq</unitOfMeasure>
		<dimensionalClass>1/T</dimensionalClass>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>amount of substance</name>
		<description>Molar amount of a substance.</description>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
		<unitOfMeasure>mol</unitOfMeasure>
		<dimensionalClass>N</dimensionalClass>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>amplitude</name>
		<description>Amplitude of the acoustic signal recorded. It is not a physical property, only a standardEnergisticsPropertyType.</description>
		<isAbstract>false</isAbstract>
		<parentKind>unitless</parentKind>
		<unitOfMeasure>Euc</unitOfMeasure>
		<dimensionalClass>0</dimensionalClass>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>angle per length</name>
		<isAbstract>true</isAbstract>
		<parentKind>quantity</parentKind>
		<unitOfMeasure>rad/m</unitOfMeasure>
		<dimensionalClass>A/L</dimensionalClass>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>angle per time</name>
		<description>The angular velocity. The rate of change of an angle.</description>
		<isAbstract>true</isAbstract>
		<parentKind>quantity</parentKind>
		<unitOfMeasure>rad/s</unitOfMeasure>
		<dimensionalClass>A/T</dimensionalClass>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>angle per volume</name>
		<isAbstract>true</isAbstract>
		<parentKind>quantity</parentKind>
		<unitOfMeasure>rad/m3</unitOfMeasure>
		<dimensionalClass>A/L3</dimensionalClass>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>angular acceleration</name>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
		<unitOfMeasure>rad/s2</unitOfMeasure>
		<dimensionalClass>A/T2</dimensionalClass>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>area</name>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
		<unitOfMeasure>m2</unitOfMeasure>
		<dimensionalClass>L2</dimensionalClass>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>area per area</name>
		<description>A dimensionless quantity where the basis of the ratio is area.</description>
		<isAbstract>true</isAbstract>
		<parentKind>dimensionless</parentKind>
		<unitOfMeasure>Euc</unitOfMeasure>
		<dimensionalClass>ratio(L2)</dimensionalClass>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>area per volume</name>
		<isAbstract>true</isAbstract>
		<parentKind>quantity</parentKind>
		<unitOfMeasure>1/m</unitOfMeasure>
		<dimensionalClass>1/L</dimensionalClass>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>attenuation</name>
		<description>A logarithmic, fractional change of some measure, generally power or amplitude, over a standard range. This is generally used for frequency attenuation over an octave.</description>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
		<unitOfMeasure>B/O</unitOfMeasure>
		<dimensionalClass>1</dimensionalClass>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>attenuation per length</name>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
		<unitOfMeasure>B/m</unitOfMeasure>
		<dimensionalClass>1/L</dimensionalClass>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>azimuth</name>
		<description>Angle between the North and the projection of the normal to the horizon surface estimated on a local area of the interface.</description>
		<isAbstract>false</isAbstract>
		<parentKind>plane angle</parentKind>
		<unitOfMeasure>rad</unitOfMeasure>
		<dimensionalClass>A</dimensionalClass>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>bubble point pressure</name>
		<description>The pressure at which the first gas bubble appears while decreasing pressure on a fluid sample.</description>
		<isAbstract>false</isAbstract>
		<parentKind>pressure</parentKind>
		<unitOfMeasure>Pa</unitOfMeasure>
		<dimensionalClass>M/LT2</dimensionalClass>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>bulk modulus</name>
		<description>Bulk modulus, K</description>
		<isAbstract>false</isAbstract>
		<parentKind>pressure</parentKind>
		<unitOfMeasure>Pa</unitOfMeasure>
		<dimensionalClass>M/LT2</dimensionalClass>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>capacitance</name>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
		<unitOfMeasure>F</unitOfMeasure>
		<dimensionalClass>C2T4/L2M</dimensionalClass>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>categorical</name>
		<description>The abstract supertype of all enumerated string properties.</description>
		<isAbstract>true</isAbstract>
		<parentKind>RESQML root property</parentKind>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>cell length</name>
		<description>distance from cell face center to cell face center in the specified direction, DI, DJ, DK</description>
		<isAbstract>false</isAbstract>
		<parentKind>length</parentKind>
		<unitOfMeasure>m</unitOfMeasure>
		<dimensionalClass>L</dimensionalClass>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>charge density</name>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
		<unitOfMeasure>C/m3</unitOfMeasure>
		<dimensionalClass>CT/L3</dimensionalClass>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>chemical potential</name>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
		<unitOfMeasure>J/mol</unitOfMeasure>
		<dimensionalClass>L2M/NT2</dimensionalClass>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>code</name>
		<description>A discrete code.</description>
		<isAbstract>false</isAbstract>
		<parentKind>categorical</parentKind>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>compressibility</name>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
		<unitOfMeasure>1/Pa</unitOfMeasure>
		<dimensionalClass>LT2/M</dimensionalClass>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>concentration of B</name>
		<description>molar concentration of a substance.</description>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
		<unitOfMeasure>mol/m3</unitOfMeasure>
		<dimensionalClass>N/L3</dimensionalClass>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>conductivity</name>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
		<unitOfMeasure>S/m</unitOfMeasure>
		<dimensionalClass>C2T3/L3M</dimensionalClass>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>continuous</name>
		<description>The abstract supertype of all floating point properties.</description>
		<isAbstract>true</isAbstract>
		<parentKind>RESQML root property</parentKind>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>cross section absorption</name>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
		<unitOfMeasure>m2/mol</unitOfMeasure>
		<dimensionalClass>L2/N</dimensionalClass>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>current density</name>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
		<unitOfMeasure>A/m2</unitOfMeasure>
		<dimensionalClass>C/L2</dimensionalClass>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>Darcy flow coefficient</name>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
		<unitOfMeasure>Pa/m3</unitOfMeasure>
		<dimensionalClass>M/L4T2</dimensionalClass>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>data transmission speed</name>
		<description>used primarily for computer transmission rates.</description>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
		<unitOfMeasure>bps</unitOfMeasure>
		<dimensionalClass>1/T</dimensionalClass>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>delta temperature</name>
		<description>Delta temperature refers to temperature differences. For non-zero offset temperature scales, Fahrenheit and Celsius, the conversion formulas are different than for absolute temperatures.</description>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
